/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GilPublisherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  targetRepoPath: "",
  publishFolder: "",
  ignoredFolders: [],
  imageTargetSubpath: "src/assets",
  notesTargetSubpath: "src/content/notes"
};
var GilPublisherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Astro repo path").setDesc(
      "Absolute path to the root of your Astro site repository (e.g. /Users/you/projects/gil.dev)"
    ).addText(
      (text) => text.setPlaceholder("/Users/you/projects/gil.dev").setValue(this.plugin.settings.targetRepoPath).onChange(async (value) => {
        this.plugin.settings.targetRepoPath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Publish folder").setDesc(
      "Only publish notes inside this vault folder (e.g. Published). Leave blank to publish all notes."
    ).addText(
      (text) => text.setPlaceholder("Published").setValue(this.plugin.settings.publishFolder).onChange(async (value) => {
        this.plugin.settings.publishFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Notes output path").setDesc("Subpath within the repo where notes are written.").addText(
      (text) => text.setPlaceholder("src/content/notes").setValue(this.plugin.settings.notesTargetSubpath).onChange(async (value) => {
        this.plugin.settings.notesTargetSubpath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Images output path").setDesc("Subpath within the repo where images are copied.").addText(
      (text) => text.setPlaceholder("src/assets").setValue(this.plugin.settings.imageTargetSubpath).onChange(async (value) => {
        this.plugin.settings.imageTargetSubpath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Ignored folders").setDesc(
      "Comma-separated list of vault folder names to skip (e.g. Templates, Archive, Private)"
    ).addText(
      (text) => text.setPlaceholder("Templates, Archive, Private").setValue(this.plugin.settings.ignoredFolders.join(", ")).onChange(async (value) => {
        this.plugin.settings.ignoredFolders = value.split(",").map((s) => s.trim()).filter(Boolean);
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/publisher.ts
var import_fs = __toESM(require("fs"));
var import_path3 = __toESM(require("path"));

// src/frontmatter.ts
var import_path = __toESM(require("path"));
var FRONTMATTER_REGEX = /^---\r?\n([\s\S]*?)\r?\n---/;
function parseFrontmatter(content) {
  const match = content.match(FRONTMATTER_REGEX);
  if (!match) return {};
  return parseSimpleYaml(match[1]);
}
function stripFrontmatter(content) {
  return content.replace(FRONTMATTER_REGEX, "").replace(/^\r?\n/, "");
}
function serializeFrontmatter(fm) {
  const lines = ["---"];
  for (const [key, value] of Object.entries(fm)) {
    if (value === void 0 || value === null) continue;
    if (Array.isArray(value)) {
      if (value.length === 0) {
        lines.push(`${key}: []`);
      } else {
        lines.push(`${key}:`);
        for (const item of value) {
          lines.push(`  - ${String(item)}`);
        }
      }
    } else if (typeof value === "boolean") {
      lines.push(`${key}: ${value}`);
    } else {
      lines.push(`${key}: ${String(value)}`);
    }
  }
  lines.push("---");
  return lines.join("\n");
}
function normalizeFrontmatter(existing, fileName, ctime, mtime) {
  const slug = typeof existing.slug === "string" && existing.slug ? existing.slug : fileNameToSlug(fileName);
  const title = typeof existing.title === "string" && existing.title ? existing.title : slugToTitle(slug);
  const date = typeof existing.date === "string" && existing.date ? ensureDateFormat(existing.date) : formatDate(ctime);
  const lastmod = typeof existing.lastmod === "string" && existing.lastmod ? ensureDateFormat(existing.lastmod) : formatDate(mtime);
  const tags = Array.isArray(existing.tags) ? existing.tags.map(String) : [];
  const result = {
    ...existing,
    title,
    slug,
    date,
    lastmod,
    tags
  };
  for (const key of Object.keys(result)) {
    if (result[key] === void 0) delete result[key];
  }
  return result;
}
function fileNameToSlug(fileName) {
  const base = import_path.default.basename(fileName, import_path.default.extname(fileName));
  return base.replace(/^\d{4}-\d{2}-\d{2}-/, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
function slugToTitle(slug) {
  return slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
function formatDate(ms) {
  const d = new Date(ms);
  const pad = (n, w = 2) => String(n).padStart(w, "0");
  const tzOffset = -d.getTimezoneOffset();
  const sign = tzOffset >= 0 ? "+" : "-";
  const absOffset = Math.abs(tzOffset);
  const tzHH = pad(Math.floor(absOffset / 60));
  const tzMM = pad(absOffset % 60);
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}${sign}${tzHH}${tzMM}`;
}
function ensureDateFormat(raw) {
  const exactMatch = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{4}$/.test(raw);
  if (exactMatch) return raw;
  const colonOffset = raw.match(/^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}):(\d{2})$/);
  if (colonOffset) return colonOffset[1] + colonOffset[2];
  if (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/.test(raw)) {
    return raw.replace("Z", "+0000");
  }
  if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) {
    return `${raw}T00:00:00+0000`;
  }
  const parsed = Date.parse(raw);
  if (!isNaN(parsed)) return formatDate(parsed);
  return raw;
}
function parseSimpleYaml(yaml) {
  var _a, _b;
  const result = {};
  const lines = yaml.split(/\r?\n/);
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const keyMatch = line.match(/^([a-zA-Z_][a-zA-Z0-9_]*):\s*(.*)?$/);
    if (!keyMatch) {
      i++;
      continue;
    }
    const key = keyMatch[1];
    const rest = (_b = (_a = keyMatch[2]) == null ? void 0 : _a.trim()) != null ? _b : "";
    if (rest === "" || rest === "|" || rest === ">") {
      const items = [];
      i++;
      while (i < lines.length && /^\s+-\s+/.test(lines[i])) {
        const item = lines[i].replace(/^\s+-\s+/, "").trim();
        items.push(item.replace(/^['"]|['"]$/g, ""));
        i++;
      }
      result[key] = items;
    } else if (rest === "null") {
      result[key] = null;
      i++;
    } else if (rest === "true") {
      result[key] = true;
      i++;
    } else if (rest === "false") {
      result[key] = false;
      i++;
    } else if (/^\[.*\]$/.test(rest)) {
      const inner = rest.slice(1, -1);
      result[key] = inner ? inner.split(",").map((s) => s.trim().replace(/^['"]|['"]$/g, "")) : [];
      i++;
    } else {
      result[key] = rest.replace(/^['"]|['"]$/g, "");
      i++;
    }
  }
  return result;
}

// src/wikilink.ts
var import_path2 = __toESM(require("path"));
var IMAGE_EXTENSIONS = /* @__PURE__ */ new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".webp",
  ".svg",
  ".avif",
  ".bmp",
  ".tiff"
]);
function isImageFile(name) {
  return IMAGE_EXTENSIONS.has(import_path2.default.extname(name).toLowerCase());
}
function transformWikilinks(content, slugMap, imageAssetsSubpath = "../../assets", publishedPaths) {
  const referencedImages = [];
  const wikilinkRegex = /(!?)\[\[([^\]|#]+)(?:#[^\]|]*)?((?:\|[^\]]*)?)\]\]/g;
  const transformed = content.replace(
    wikilinkRegex,
    (_, bang, target, aliasPart) => {
      const isEmbed = bang === "!";
      const alias = aliasPart ? aliasPart.slice(1) : "";
      const trimmedTarget = target.trim();
      if (isEmbed && isImageFile(trimmedTarget)) {
        const imgName = import_path2.default.basename(trimmedTarget);
        referencedImages.push(trimmedTarget);
        const displayAlt = alias || imgName;
        return `![${displayAlt}](${imageAssetsSubpath}/${imgName})`;
      }
      const entry = resolveEntry(trimmedTarget, slugMap);
      const displayText = alias || trimmedTarget;
      if (!entry) {
        return displayText;
      }
      if (publishedPaths && !publishedPaths.has(entry.sourcePath)) {
        return displayText;
      }
      return `[${displayText}](/${entry.slug})`;
    }
  );
  return { transformed, referencedImages };
}
function resolveEntry(target, slugMap) {
  const stem = import_path2.default.basename(target, import_path2.default.extname(target));
  if (slugMap.has(stem)) return slugMap.get(stem);
  const lower = stem.toLowerCase();
  for (const [key, entry] of slugMap) {
    if (key.toLowerCase() === lower) return entry;
  }
  for (const [key, entry] of slugMap) {
    if (key.toLowerCase() === target.toLowerCase()) return entry;
  }
  return null;
}

// src/publisher.ts
function buildSlugMap(app, ignoredFolders) {
  const map = /* @__PURE__ */ new Map();
  const files = app.vault.getMarkdownFiles();
  for (const file of files) {
    if (isInIgnoredFolder(file.path, ignoredFolders)) continue;
    const stem = import_path3.default.basename(file.path, import_path3.default.extname(file.path));
    const slug = frontmatterSlugOrDerived(app, file);
    const entry = { slug, sourcePath: file.path };
    map.set(stem, entry);
    const title = frontmatterTitle(app, file);
    if (title && title.toLowerCase() !== stem.toLowerCase()) {
      map.set(title, entry);
    }
  }
  return map;
}
function buildPublishedPaths(app, settings) {
  const files = app.vault.getMarkdownFiles();
  return new Set(
    files.filter((f) => !isInIgnoredFolder(f.path, settings.ignoredFolders)).filter((f) => isInPublishFolder(f.path, settings.publishFolder)).map((f) => f.path)
  );
}
async function publishAll(app, settings, onProgress) {
  const result = { published: [], skipped: [], errors: [] };
  if (!settings.targetRepoPath) {
    result.errors.push({ file: "", error: "Target repo path is not configured." });
    return result;
  }
  const slugMap = buildSlugMap(app, settings.ignoredFolders);
  const files = app.vault.getMarkdownFiles();
  const publishedPaths = buildPublishedPaths(app, settings);
  for (const file of files) {
    if (isInIgnoredFolder(file.path, settings.ignoredFolders)) {
      result.skipped.push(file.path);
      continue;
    }
    if (!isInPublishFolder(file.path, settings.publishFolder)) {
      result.skipped.push(file.path);
      continue;
    }
    try {
      onProgress == null ? void 0 : onProgress(`Publishing ${file.path}\u2026`);
      await publishFile(app, file, settings, slugMap, publishedPaths);
      result.published.push(file.path);
    } catch (err) {
      result.errors.push({ file: file.path, error: String(err) });
    }
  }
  return result;
}
async function publishFile(app, file, settings, slugMap, publishedPaths) {
  var _a, _b;
  const raw = await app.vault.read(file);
  const stat = await app.vault.adapter.stat(file.path);
  const existingFm = parseFrontmatter(raw);
  const normalizedFm = normalizeFrontmatter(
    existingFm,
    file.name,
    (_a = stat == null ? void 0 : stat.ctime) != null ? _a : Date.now(),
    (_b = stat == null ? void 0 : stat.mtime) != null ? _b : Date.now()
  );
  const body = stripFrontmatter(raw);
  const imageAssetsSubpath = buildImageRelativePath(settings);
  const { transformed, referencedImages } = transformWikilinks(
    body,
    slugMap,
    imageAssetsSubpath,
    publishedPaths
  );
  const assetsDir = import_path3.default.join(settings.targetRepoPath, settings.imageTargetSubpath);
  await ensureDir(assetsDir);
  for (const imgPath of referencedImages) {
    await copyImage(app, imgPath, assetsDir);
  }
  const notesDir = import_path3.default.join(settings.targetRepoPath, settings.notesTargetSubpath);
  await ensureDir(notesDir);
  const outputName = import_path3.default.basename(file.path);
  const outputPath = import_path3.default.join(notesDir, outputName);
  const outputContent = serializeFrontmatter(normalizedFm) + "\n\n" + transformed;
  import_fs.default.writeFileSync(outputPath, outputContent, "utf-8");
}
function isInIgnoredFolder(filePath, ignoredFolders) {
  if (ignoredFolders.length === 0) return false;
  const parts = filePath.split("/");
  return parts.some((part) => ignoredFolders.includes(part));
}
function isInPublishFolder(filePath, publishFolder) {
  if (!publishFolder) return true;
  const prefix = publishFolder.endsWith("/") ? publishFolder : publishFolder + "/";
  return filePath.startsWith(prefix);
}
function frontmatterSlugOrDerived(app, file) {
  var _a;
  const cache = app.metadataCache.getFileCache(file);
  const fm = (_a = cache == null ? void 0 : cache.frontmatter) != null ? _a : {};
  if (typeof fm.slug === "string" && fm.slug) return fm.slug;
  const stem = import_path3.default.basename(file.path, import_path3.default.extname(file.path));
  return stem.replace(/^\d{4}-\d{2}-\d{2}-/, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
function frontmatterTitle(app, file) {
  var _a;
  const cache = app.metadataCache.getFileCache(file);
  const fm = (_a = cache == null ? void 0 : cache.frontmatter) != null ? _a : {};
  return typeof fm.title === "string" ? fm.title : null;
}
async function copyImage(app, imgPath, destDir) {
  const vaultFiles = app.vault.getFiles();
  const match = vaultFiles.find(
    (f) => f.path === imgPath || f.name === import_path3.default.basename(imgPath) || isImageFile(f.name) && f.name === imgPath
  );
  if (!match) return;
  const data = await app.vault.readBinary(match);
  const destPath = import_path3.default.join(destDir, match.name);
  import_fs.default.writeFileSync(destPath, Buffer.from(data));
}
function ensureDir(dir) {
  if (!import_fs.default.existsSync(dir)) {
    import_fs.default.mkdirSync(dir, { recursive: true });
  }
}
function buildImageRelativePath(settings) {
  const notesDepth = settings.notesTargetSubpath.split("/").length;
  const ups = "../".repeat(notesDepth);
  const imgSubpath = settings.imageTargetSubpath;
  return (ups + imgSubpath).replace(/\/+$/, "");
}

// src/main.ts
var GilPublisherPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new GilPublisherSettingTab(this.app, this));
    this.addCommand({
      id: "publish-all-notes",
      name: "Publish all notes to site",
      callback: async () => {
        if (!this.settings.targetRepoPath) {
          new import_obsidian2.Notice(
            "Gil Publisher: Set the Astro repo path in plugin settings first.",
            5e3
          );
          return;
        }
        new import_obsidian2.Notice("Gil Publisher: Starting full publish\u2026");
        const result = await publishAll(this.app, this.settings, (msg) => {
          console.log("[GilPublisher]", msg);
        });
        const summary = `Published ${result.published.length} notes` + (result.skipped.length ? `, skipped ${result.skipped.length}` : "") + (result.errors.length ? `, ${result.errors.length} error(s)` : "") + ".";
        new import_obsidian2.Notice(`Gil Publisher: ${summary}`, 8e3);
        if (result.errors.length) {
          console.error("[GilPublisher] Errors:", result.errors);
        }
      }
    });
    this.addCommand({
      id: "publish-current-note",
      name: "Publish current note to site",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file || file.extension !== "md") return false;
        if (checking) return true;
        if (!this.settings.targetRepoPath) {
          new import_obsidian2.Notice(
            "Gil Publisher: Set the Astro repo path in plugin settings first.",
            5e3
          );
          return;
        }
        const slugMap = buildSlugMap(this.app, this.settings.ignoredFolders);
        const publishedPaths = buildPublishedPaths(this.app, this.settings);
        publishFile(this.app, file, this.settings, slugMap, publishedPaths).then(() => {
          new import_obsidian2.Notice(`Gil Publisher: Published "${file.basename}".`);
        }).catch((err) => {
          new import_obsidian2.Notice(`Gil Publisher: Error publishing "${file.basename}": ${String(err)}`, 8e3);
          console.error("[GilPublisher]", err);
        });
      }
    });
    this.addRibbonIcon("upload", "Publish current note", async () => {
      const file = this.app.workspace.getActiveFile();
      if (!file || file.extension !== "md") {
        new import_obsidian2.Notice("Gil Publisher: Open a markdown note first.");
        return;
      }
      if (!this.settings.targetRepoPath) {
        new import_obsidian2.Notice(
          "Gil Publisher: Set the Astro repo path in plugin settings first.",
          5e3
        );
        return;
      }
      const slugMap = buildSlugMap(this.app, this.settings.ignoredFolders);
      const publishedPaths = buildPublishedPaths(this.app, this.settings);
      try {
        await publishFile(this.app, file, this.settings, slugMap, publishedPaths);
        new import_obsidian2.Notice(`Gil Publisher: Published "${file.basename}".`);
      } catch (err) {
        new import_obsidian2.Notice(`Gil Publisher: Error \u2014 ${String(err)}`, 8e3);
        console.error("[GilPublisher]", err);
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
